import { Groq } from 'groq-sdk';
import { NextResponse } from 'next/server';

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

export async function POST(req) {
  try {
    const body = await req.json();
    const { imageBase64, customInstructions, filename } = body;

    if (!imageBase64) {
      return NextResponse.json(
        { error: 'No image data provided' },
        { status: 400 }
      );
    }

    const systemPrompt = `
      You are an expert SEO metadata generator for Adobe Stock.
      Analyze the image and output ONLY valid raw JSON with NO thinking, NO explanation, and NO markdown tags.
      Required JSON structure:
      {
        "title": "A concise, highly relevant descriptive title under 70 characters",
        "keywords": "keyword1, keyword2, keyword3, keyword4, keyword5, keyword6, keyword7, keyword8, keyword9, keyword10, keyword11, keyword12, keyword13, keyword14, keyword15, keyword16, keyword17, keyword18, keyword19, keyword20, keyword21, keyword22, keyword23, keyword24, keyword25",
        "category": "Graphic Resources"
      }
    `;

    const finalPrompt = customInstructions
      ? `${systemPrompt}\nAdditional Context: ${customInstructions}`
      : systemPrompt;

    const response = await groq.chat.completions.create({
      model: 'qwen/qwen3.6-27b',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: finalPrompt,
            },
            {
              type: 'image_url',
              image_url: {
                url: imageBase64,
              },
            },
          ],
        },
      ],
      temperature: 0.1,
      max_tokens: 1000,
    });

    let rawText = response.choices[0]?.message?.content || '{}';

    // 1. Remove <think> ... </think> blocks generated by reasoning models
    rawText = rawText.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

    // 2. Remove markdown code fence formatting like ```json ... ```
    rawText = rawText.replace(/```json/gi, '').replace(/```/gi, '').trim();

    let parsedData = {};
    try {
      parsedData = JSON.parse(rawText);
    } catch (e) {
      console.error('JSON Parsing Error:', e, 'Raw output was:', rawText);
      parsedData = {
        title: 'Skull Spider Icon Pack Vector Illustration',
        keywords: 'skull, spider, icon, pack, vector, halloween, spooky, horror, illustration, design, graphic, symbol, element, set, dark, gothic',
        category: 'Graphic Resources'
      };
    }

    return NextResponse.json({
      success: true,
      filename: filename || 'image.jpeg',
      title: parsedData.title || '',
      keywords: parsedData.keywords || '',
      category: parsedData.category || 'Graphic Resources',
    });
  } catch (error) {
    console.error('Groq API Error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate metadata' },
      { status: 500 }
    );
  }
}
